### ISSUE TITLE
Add a master version

### ISSUE THREAD

**Issue by lukeapage** [bfricka/less-preview#7]
It shouldn't by default, but master branch version (or e.g. "1.4.0 alpha") allows people to play with new features

**Comment by scottrippey** [comment]
I'm absolutely on-board with this idea!  This is my personal '#1' feature request.
However, currently, we use the `/cloudhead/less.js/dist/*` folder to include each version of LESS on the page.  As far as I know, there is no compiled `less.1.4.0 alpha.js` in the repo.  

So, I think there's 2 ways of getting this implemented:
1. We add a new Less version, "1.4.0 nightly" that imports the necessary files directly from `/less.js/lib/`.  I'd need help to do this, because I'm not sure if the Less sources can be included without being built.
2. We add a new folder to the Less repo, `/less.js/pre-dist/` or something, where we put the compiled `less.1.4.0.alpha.js`.

**Comment by lukeapage** [comment]
hrmm then its going to start picking up 1.4.0 soon...
https://github.com/cloudhead/less.js/tree/master/dist

Its quite easy to make less.js from the sources..
https://github.com/cloudhead/less.js/blob/master/Makefile#L26

I could rename the one in dist to add alpha to it (I probably should) but it is a pain compiling with every commit (I've done it every 6 or so)

**Comment by lukeapage** [comment]
Have updated the files to include a alpha in the name.

Though I am thinking of only doing this alpha release because 1.4.0 is so big and has some breaking changes.. so it would be good to make your own from the source.

**Comment by scottrippey** [comment]
I think it might be a bad idea to be compiling "nightlies" to the `/dist/` folder.  I wouldn't expect anything to ever change in that folder.  Even calling it `alpha` says to me, "go ahead and start testing, this is the official alpha release".  And I wouldn't commit anything to the `/dist/` folder that isn't permanent.  
My recommendation is a completely separate `/nightly/` folder (or any appropriate word will do, 'latest', 'alpha', 'beta', etc).

Once you settle on a name, I'll add that to the less2css dropdown, so you can update and test with ease :)

**Comment by bfricka** [comment]
So I rewrote this thing in Express so we can have a nice MVC server-side component with easy APIs.

The list is now populated by a `lessVersions.js`, which is set as an app variable via require.  It's all written in coffee-script and it looks like this:

``` coffee
exports.lessVersions = [
  {number: "1.4.0", type: "pre"}
  {number: "1.3.3", type: "current"}
  {number: "1.3.2", type: "old"}
  {number: "1.3.1", type: "old"}
  # ...
]
```

The Jade template then renders the list using a conditional that:
- Checks for type `pre` and renders a data-attribute that will allow us to point pre-release paths. Also appends (pre-release) next to the version on the drop down so it's clear to people.
- Checks for type `current` and gives makes it the selected value. Also appends (current) next to the version.
- The rest render out normally.

The makes managing the list simple.  The key is that the path for pre-release versions follow a convention that we can agree on.  Personally, I don't care whether you use alpha in dist, or add something else. As long as you can keep it consistent, I will be appreciative.

I'll commit the express branch shortly, but it won't be actually deployed immediately.  Still have to solidify the setup on my VPS.

Additionally, I'll be adding notes for potential contributors on how to build.  I can also provide git > push access for contributors who want to push directly to the live server.

Anyways, let me know what you decide re: pre-lease stuff.  For now I'll assume you're just appending `-alpha`. Thanks.

**Comment by scottrippey** [comment]
@brian-frichette   Maybe,  for each `lessVersion`,  you could  just add a "src" property.  that way,  you could include custom forks and stuff.

 I was originally thinking of just putting this info directly in the html,  such as `<option  value="http://.../less.1.4.0.alpha.js" >1.4.0 Alpha</option>`

**Comment by bfricka** [comment]
This is done and live.  I don't have much opinion on how to handle this, Scott. I'm happy having it in a single file, but I'm open to alternatives.

In order to support IE (including 9-10), I'll need to have a locally hosted version of this anyways, so when I get a chance, I'll put something into my build script that pulls down files and builds less from source.  I'll setup a cron to do it every day (a la 'nightlies').
